name: deploy

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-18.04
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2 # Atualizado para a versão 2 do setup-node
with:
node-version: '14' # Atualizado para a versão 14 do Node.js
- name: Build web-app
run: |
npm ci
npm run build
- name: Deploy to gh-pages
uses: peaceiris/actions-gh-pages@v3
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./build